### ISSUE TITLE
Mini Auth doesn't catch simultaneous connections 

### ISSUE THREAD

**Issue by Kei-Shin** [new-frontiers-14/frontier-station-14#1520]
## Description
You can evade mini auth but joining both servers at the same time.

**Reproduction**
1. Open up ss14 launcher
2. Click to join first server (ie Maunder)
3. Be ready to repeat step 2 but for the other server (ie Hypatia) while the launcher processes other things.
(Might take multiple attempts but you get the idea)

**Screenshots**
https://github.com/new-frontiers-14/frontier-station-14/assets/22483737/0d66d8f6-5b5c-4bf5-a367-fa02ad29ba4c

**Additional context**
This could likely be fixed by doing either periodic checks or maybe event listeners of some kind idk. (Haven't used C# in 8 years or so) Alternatively and this is probably out of scope / too much work but setting it up so instead it prevents the user from controlling anything other than ghosts since spectating both servers is kinda nice imo.

**Comment by Cheackraze** [comment]
Just so everybody is aware, anybody caught exploiting or brute forcing measures like this, including using 3rd party software, will be banned from official frontier servers. We dont have the capability for perfect auth checks and intentionally trying to bypass them in unintended ways will be seen as direct, intentional exploits on our servers.
