### ISSUE TITLE
Signature stamp needs its own entity

### ISSUE THREAD

**Issue by Cheackraze** [new-frontiers-14/frontier-station-14#327]
## Description

overriding an existing stamp makes no sense
**Reproduction**

**Additional context**

we should add the signature functionality to the PDA or something instead, so that anyone can sign papers and you don't have to use some strange object that doesn't make sense.

**Comment by dvir001** [comment]
It can be its own entity or use another entity, I made the code so it can be assigned to other stuff.
Do keep in mind that putting it on PDA or your card will need to have the code read from the card or PDA in your hand and not the one equipped, so a bit of a code change if we do this, nothing major. (You dont want it to read the user entity since it won't account for name changes or fake cards)

Also I find that using a PDA or Card to stamp is anti RP since its not a stamp, unlike an actual stamp.

On another note, the captain stamp had no actual use since captain means nothing when everyone are captain.
There is a PR to add the stamp to crates and SR vend machine to make it possible to buy it, also its coming in the captain locker if we remap it.

I also left the part of the code that add your rank to the stamp uncommented, it can say "Captain NAME" or "RANK NAME" instead.

**Comment by Cheackraze** [comment]
I mean it's a signature right? Maybe making it a right click verb with just any pen? That isn't great either because it kind of hides the function.  The thing is not everyone is captain all the time but imo there's no reason why anyone shouldn't be able to sign a paper

**Comment by dvir001** [comment]
> I mean it's a signature right? Maybe making it a right click verb with just any pen? That isn't great either because it kind of hides the function. The thing is not everyone is captain all the time but imo there's no reason why anyone shouldn't be able to sign a paper

Ill try to think about some way to implement it on a more simple way, if we consider it signature ill also need to remove the "stamp" outline so it also adding up
![image](https://github.com/new-frontiers-14/frontier-station-14/assets/39403717/d3a52853-3832-4f65-9e56-6f2e0f47f5b9)

In the main time I can remove the "captain" word from the stamp name to have be more logical as a general use stamp

**Comment by dvir001** [comment]
Fixed and done with https://github.com/new-frontiers-14/frontier-station-14/pull/349
